# Generated by Django 5.1 on 2024-09-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=14)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('designation', models.CharField(choices=[('manager', 'Manager'), ('accountant', 'Accountant'), ('hr', 'HR'), ('developer', 'Software Developer'), ('intern', 'Intern')], max_length=20)),
            ],
        ),
    ]
