# Generated by Django 5.1 on 2024-09-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_data', '0003_e_data_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_data',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
