# Generated by Django 5.1 on 2024-09-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_data', '0005_alter_e_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_data',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='e_data',
            name='designation',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Accountant', 'Accountant'), ('HR', 'HR'), ('Software Developer', 'Software Developer'), ('Intern', 'Intern')], max_length=20),
        ),
        migrations.AlterField(
            model_name='e_data',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
