# Generated by Django 5.1 on 2024-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_data', '0006_e_data_description_alter_e_data_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_data',
            name='employee',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
