# Generated by Django 5.1.1 on 2024-09-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
