# Generated by Django 5.1 on 2024-08-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
